In [1]:
import torch

In [2]:
torch.ones(size=(2,1))

tensor([[1.],
        [1.]])

In [3]:
torch.zeros(size=(2,1))

tensor([[0.],
        [0.]])

In [4]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [7]:
torch.normal(
    mean=torch.zeros(size=(3, 1)), 
    std=t orch.ones(size=(3, 1))
)

tensor([[-0.8881],
        [ 0.1185],
        [-0.9108]])

In [9]:
torch.rand(3, 1)

tensor([[0.9015],
        [0.2103],
        [0.3009]])