In [1]:
import tensorflow as tf

In [2]:
tf.ones(shape=(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [3]:
tf.zeros(shape=(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [4]:
tf.constant([1, 2, 3], dtype="float32")

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
x = tf.random.normal(shape=(3,1), mean=0, stddev=1)

In [6]:
print(x)

tf.Tensor(
[[ 1.0396807 ]
 [ 0.24989043]
 [-0.94213474]], shape=(3, 1), dtype=float32)


In [9]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))

In [12]:
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [13]:
a=tf.ones(2, 2)

In [14]:
b = tf.square(a)

In [15]:
print(b)

tf.Tensor([1. 1.], shape=(2,), dtype=float64)


In [16]:
b

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 1.])>

In [17]:
input_var = tf.Variable(initial_value=3.)

In [19]:
with tf.GradientTape() as tape:
    result = tf.square(input_var)

In [20]:
x = tape.gradient(result, input_var)

In [21]:
print(x)

tf.Tensor(6.0, shape=(), dtype=float32)
